### ISSUE TITLE
support strike-through, sub and superscript

### ISSUE THREAD

**Issue by maxandersen** [maxandersen/gdoc2adoc#7]
asciidoctor google store extension uses `<s>strike</s>` and asciidoctor docs says `[line-through]#strike#` should work (but be deprecated) but neither does not seem to render in asciidoc.js nor asciidoctor output.

**Comment by maxandersen** [comment]
@mojavelinux any recommendations on how to best represent strike-through and even sub/super-script which seem to be similar not working for me in asciidoc.js.

**Comment by mojavelinux** [comment]
It's important to understand that `line-through` is just a CSS role. Therefore, it needs support from the stylesheet in order to appear as though it is working.

If I run the following through Asciidoctor (or Asciidoctor.js):

```
[.line-through]#strike#
```

I get:

```
<span class="line-through">strike</span>
```

The default stylesheet has a rule for this:

```
.line-through{text-decoration:line-through}
```

You would need to do the same.

It is possible to customize the HTML that is generated using custom templates (Asciidoctor.js supports Jade templates). In that case, you'd override the template for inline_quoted, check for the `line-through` role and produce either an `<s>` or, preferably, a `<del>` instead of the span.

An enhancement to produce the `<del>` element is currently being deliberated. See https://github.com/asciidoctor/asciidoctor/issues/1030.

**Comment by mojavelinux** [comment]
> It is possible to customize the HTML that is generated using custom templates (Asciidoctor.js supports Jade templates). 

We need documentation for doing this. Even I'm not exactly sure how to set it up (it's been on my list). But I know it's possible because it is used in AsciidocFx.

**Comment by maxandersen** [comment]
Got it! I figured out why I could not get it to work. I had `[.line-through]# strike #` so I need to trim it ;)

**Comment by mojavelinux** [comment]
Yep, that would be a problem. If the formatting marks aren't directly adjacent to a word boundary, you'd need to double them up.

```
[.line-through]## strike ##
```

**Comment by sergeevabc** [comment]
No printed words would express my indignation of how strike-through is ~~screwed up~~ implemented here. Instead of considering an intuitive and easy-to-remember for non-English speakers approach of Markdown’s ```~~gluttony~~```, we have ```(bracket)(dot)line(dash)tRhOHgwat?(bracket)##(space)gluttony(space)##```. Damn, even HTML’s ```<s>…</s>``` or ```<del>…</del>``` is easier to remember.
